### ISSUE TITLE
could not load library "/usr/lib/postgresql/10/lib/yeti_pg_ext.so": /usr/lib/postgresql/10/lib/yeti_pg_ext.so: undefined symbol: nn_recv

### ISSUE THREAD

**Issue by katya-s** [yeti-switch/yeti-pg-ext#5]
```
postgres=# create extension yeti;
ERROR:  could not load library "/usr/lib/postgresql/10/lib/yeti_pg_ext.so": /usr/lib/postgresql/10/lib/yeti_pg_ext.so: undefined symbol: nn_recv
postgres=#
 ```
Version: PostgreSQL 10.2 (Debian 10.2-1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 7.3.0-1) 7.3.0, 64-bit
Debian version: buster/sid

**Comment by furmur** [comment]
try to install `libnanomsg-dev` package before yeti_pg_ext build.
https://github.com/yeti-switch/yeti-pg-ext/blob/master/debian/control.in#L5

**Comment by katya-s** [comment]
It works now
